### ISSUE TITLE
libvex returns incorrect jumpkind for arm instruction (thumb mode) - LDR PC, [SP],#4

### ISSUE THREAD

**Issue by ArtemShypotilov** [angr/pyvex#90] opened 2017-09-27 11:00 UTC
Hi Guys!

Current libvex version incorrectly determines jumpkind when processing instruction LDR PC, [SP],#4.

It puts Ijk_Boring, but should be Ijk_Ret.

Please see example in wget binary:

[wget.zip](https://github.com/angr/pyvex/files/1336749/wget.zip)

Function - sub_227D0, block start addr - 00022878, ret instr addr - 00022890.

Could you please add patch for that?

Thanks.

**Comment by ltfish** [comment] 2017-09-28 17:27
Thanks for reporting this issue. The way that we handle it is in post-processing phase in PyVEX. We won't produce a patch for libvex (because we do not maintain libvex, and we do not think they care about this types of issues).

**Comment by ArtemShypotilov** [comment] 2017-09-28 18:01
Guys,

But don't you already have https://github.com/angr/pyvex/tree/master/patches for such kind of issues?

We just need to add 1 string of code to https://github.com/angr/vex/tree/master/priv/guest_arm_toIR.c to correctly handle this.

This problem considerably messes CFGFast for arm binaries.

**Comment by rhelmot** [comment] 2017-09-28 19:01
That patches directory should probably be removed since we're maintaining a full fork, regardless of what fish just said.

If you think you know what the change should be (the "one string of code"), it can absolutely belong in libvex proper, and you should submit a pull request. The issue is making sure that these changes are sound. It's passable to have a call/return in ARM that is only marked as boring, but it's very nasty to have a normal transition that gets marked as a call or return for some reason.

**Comment by rhelmot** [comment] 2017-09-28 19:04
It occurs to me since this issue is on the pyvex repository and you mention the obsolete patches directory you might not know about the https://github.com/angr/vex repo

**Comment by ltfish** [comment] 2017-09-28 21:26
Loading values into PC can be either a jump or a return. Do you know how we can different between the two cases without having a global view of the function?

I don't think it is possible (feel free to correct me if I'm wrong), so it's probably better to handle this case in CFG, instead of changing the lifter code. What do you think?

**Comment by ltfish** [comment] 2017-09-28 21:27
"different" -> differentiate

There is no edit button in the mobile version...

**Comment by ArtemShypotilov** [comment] 2017-09-29 08:47
Fish,

There is really no way to differentiate, between a jump or return when PC is loaded.

However, libvex already has some code where load/mov pc variants are assumed to be Ijk_Ret.

Below are examples from https://github.com/angr/vex/tree/master/priv/guest_arm_toIR.c:

```
....
   /* According to the Cortex A8 TRM Sec. 5.2.1, LDM(1) with r13 as the base
       register and PC in the register list is a return for purposes of branch
       prediction.
      The ARM ARM Sec. C9.10.1 further specifies that writeback must be enabled
       to be counted in event 0x0E (Procedure return).*/
   if (rN == 13 && bL == 1 && bINC && !bBEFORE && bW == 1) {
      jk = Ijk_Ret;
}

....


            /* According to the Cortex A8 TRM Sec. 5.2.1, MOV PC, r14 is a
                return for purposes of branch prediction. */
            if (!isMVN && INSN(11,0) == 14) {
              jk = Ijk_Ret;
}
....

          /* According to the Cortex A8 TRM Sec. 5.2.1, LDR(1) with r13 as the
               base register and PC as the destination register is a return for
               purposes of branch prediction.
              The ARM ARM Sec. C9.10.1 further specifies that it must use a
               post-increment by immediate addressing mode to be counted in
               event 0x0E (Procedure return).*/
           if (rN == 13 && summary == (3 | 16) && bB == 0) {
              jk = Ijk_Ret;
}

....
```
Case for **LDR PC, [SP],#4** is in no way different from the ones mentioned above. libvex developers had even left comment  about that: 

```
....
   /* ---------------- LD/ST reg+/-#imm8 ---------------- */
   /* Loads and stores of the form:
         op  Rt, [Rn, #-imm8]      or
         op  Rt, [Rn], #+/-imm8    or
         op  Rt, [Rn, #+/-imm8]!  
      where op is one of
         ldrb ldrh ldr  ldrsb ldrsh
         strb strh str
   */
....  
            if (loadsPC) {
               /* Presumably this is an interworking branch. */
               vassert(rN != 15); // assured by validity check above
               vassert(rT == 15);
               vassert(condT == IRTemp_INVALID); /* due to check above */
               llPutIReg(15, mkexpr(newRt));
               dres.jk_StopHere = Ijk_Boring;  /* or _Ret ? */
               dres.whatNext    = Dis_StopHere;
}
....
```

They definitely had doubts whether it is Ijk_Boring or Ijk_Ret, but probably didn't have enough time or resources to thoroughly check that.

I'll prepare pull request for https://github.com/angr/vex and show you guys.

**Comment by ArtemShypotilov** [comment] 2017-09-29 09:47
Created pull request:

https://github.com/angr/vex/pull/13

**Comment by ltfish** [comment] 2017-09-29 13:23
Merged. Can you please confirm that it fixes your issue? I'm in the middle of nowhere and my Internet connection is funky.

**Comment by ArtemShypotilov** [comment] 2017-09-29 13:45
Fish,

Yes, issue is gone, works fine now.

Thanks.

**Comment by ltfish** [comment] 2017-09-30 01:39
Thank you!

**Closed by ltfish** 2017-09-30 01:39 UTC
Labels: enhancement
